# Generated by Django 5.2.17 on 2026-09-18 15:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InjectedAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ROUNDING', 'Rounding'), ('TIMING', 'Timing'), ('FX', 'Foreign exchange'), ('TRUE_BREAK', 'True break'), ('MISSING_IN_LEDGER', 'Missing from chart of accounts'), ('MISSING_FROM_TRIAL_BALANCE', 'Missing from trial balance')], max_length=32)),
                ('account_code', models.CharField(max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('magnitude', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
            ],
            options={
                'ordering': ['kind', 'account_code'],
            },
        ),
        migrations.CreateModel(
            name='LegacyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=16)),
                ('normal_balance', models.CharField(default='DEBIT', max_length=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('include_in_trial_balance', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LegacyDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeded_at', models.DateTimeField(auto_now=True)),
                ('seed', models.IntegerField(default=0)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('as_of_date', models.DateField(help_text='Cutover date the reconciliation is expected to use.')),
                ('account_count', models.IntegerField(default=0)),
                ('entry_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'legacy dataset',
            },
        ),
        migrations.CreateModel(
            name='LegacyJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True)),
                ('entry_date', models.DateField()),
                ('memo', models.CharField(blank=True, default='', max_length=400)),
                ('status', models.CharField(default='POSTED', max_length=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'ordering': ['entry_date', 'ref'],
                'indexes': [models.Index(fields=['entry_date'], name='legacy_entry_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegacyJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64)),
                ('debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='legacy_sim.legacyaccount')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='legacy_sim.legacyjournalentry')),
            ],
            options={
                'ordering': ['entry_id', 'id'],
                'indexes': [models.Index(fields=['account', 'entry'], name='legacy_line_acct_entry_idx')],
            },
        ),
    ]
