# Generated by Django 5.2.17 on 2026-09-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedLegacyRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ACCOUNT', 'Account'), ('ENTRY', 'Journal entry')], max_length=8)),
                ('external_ref', models.CharField(max_length=64)),
                ('source_page', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('normalised', models.JSONField(blank=True, null=True)),
                ('staged_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_rows', to='ledger.migrationjob')),
            ],
            options={
                'ordering': ['job', 'kind', 'source_page', 'id'],
                'indexes': [models.Index(fields=['job', 'kind'], name='staged_job_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'kind', 'external_ref'), name='uniq_staged_job_kind_ref')],
            },
        ),
    ]
