# Generated by Django 5.2.17 on 2026-09-18 15:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_reference', models.CharField(max_length=120)),
                ('source_system', models.CharField(max_length=32)),
                ('as_of_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('NEEDS_REVIEW', 'Needs review')], default='PENDING', max_length=16)),
                ('temporal_workflow_id', models.CharField(blank=True, default='', max_length=200)),
                ('temporal_run_id', models.CharField(blank=True, default='', max_length=200)),
                ('executor', models.CharField(blank=True, default='', max_length=16)),
                ('counters', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=16)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], db_index=True, max_length=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('external_ref', models.CharField(blank=True, default='', max_length=64)),
                ('source_system', models.CharField(blank=True, default='', max_length=32)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ledger.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('external_ref', models.CharField(max_length=64)),
                ('entry_date', models.DateField(db_index=True)),
                ('memo', models.CharField(blank=True, default='', max_length=400)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='POSTED', max_length=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('fx_rate', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['entry_date', 'id'],
                'indexes': [models.Index(fields=['entry_date', 'status'], name='entry_date_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'external_ref'), name='uniq_entry_source_ref')],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('external_ref', models.CharField(blank=True, default='', max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=48)),
                ('actor', models.CharField(default='system', max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='ledger.migrationjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('EXTRACT', 'Extract'), ('STAGE', 'Stage'), ('TRANSFORM', 'Transform'), ('VALIDATE', 'Validate'), ('LOAD', 'Load'), ('RECONCILE', 'Reconcile')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=12)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('chunk', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='ledger.migrationjob')),
            ],
            options={
                'ordering': ['job', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField()),
                ('status', models.CharField(default='COMPLETED', max_length=16)),
                ('legacy_total_debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('legacy_total_credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('loaded_total_debit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('loaded_total_credit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('legacy_entry_count', models.IntegerField(default=0)),
                ('loaded_entry_count', models.IntegerField(default=0)),
                ('difference', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('duration_ms', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='ledger.migrationjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=32)),
                ('account_name', models.CharField(blank=True, default='', max_length=160)),
                ('legacy_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('loaded_balance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('variance', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('ROUNDING', 'Rounding'), ('TIMING', 'Timing'), ('FX', 'Foreign exchange'), ('MAPPING_ERROR', 'Mapping error'), ('TRUE_BREAK', 'True break')], default='UNCLASSIFIED', max_length=16)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=8)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=400)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='ledger.reconciliationrun')),
            ],
            options={
                'ordering': ['-variance', 'account_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('external_ref',), name='uniq_account_external_ref'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('code',), name='uniq_account_code'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'entry'], name='line_account_entry_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gt', 0), ('debit__gt', 0), _negated=True), name='line_single_sided'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _connector='OR'), name='line_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='line_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('entry', 'external_ref'), name='uniq_line_entry_external_ref'),
        ),
        migrations.AddIndex(
            model_name='reconciliationbreak',
            index=models.Index(fields=['run', 'resolved'], name='break_run_resolved_idx'),
        ),
    ]
