# Generated by Django 5.2.17 on 2026-09-18 16:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_integrity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconciliationbreak',
            options={'ordering': ['variance_rank', 'account_code']},
        ),
        migrations.AddField(
            model_name='migrationphase',
            name='label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='cumulative_variance_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='reconciliationbreak',
            name='variance_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit', to='ledger.migrationjob'),
        ),
    ]
